In [5]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

<img src="./jak_dziala_meshgrid.png" alt="obrazek" width="1300" />

# <b> ogólnie, kiedy uywać indeksowania xy a kiedy ij (transponowanego)  </b>
używać indeksowania <b>indexing='ij'</b> jak pracuje z funkcjami z meshgrid
wtedy myśle o: $$z[:, 3]$$ jako o przekroju $$z\ od\ x\ dla\ y=3$$
albo: wszystkie elementy pierwszej osi, w miejscu 3 drugiej osi\
albo: wartości dla Z od pierwszej osi, w miejscu 3 drugiej osi

<b>Ale </b>

jak pracuje np. z obrazami w grey-scale'u (tablice 2D)
to wole myśleć o $$img[:, 3]$$ jako o TRZECI element ze wszystkich RZĘDÓW (third element in all rows / third column elements)\
albo: po prostu <b>"trzecia kolumna"</b>\

Więc aby zmienić każdą macierz / tablice 2D na indeksowanie macierzowe -> TRANSPOZYCJA



### <b> Indeksowanie $ij$ "macierzowe" oraz sprase=True/false

In [6]:
x = np.arange(0, 6, 1)
y = np.arange(0, 10, 1)

In [7]:
xx_ij, yy_ij = np.meshgrid(x, y, indexing='ij')
z_ij = xx_ij + 2*yy_ij
display(z_ij)
z_ij[:, 4]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21],
       [ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

array([ 8,  9, 10, 11, 12, 13])

In [8]:
# Jeżeli funkcja (z_ij) zależy od wszystkich osi (zmiennych) to można użyć sparse=True
xx_ij, yy_ij = np.meshgrid(x, y, indexing='ij',sparse=True)
z_ij = xx_ij + 2*yy_ij
display(z_ij)
z_ij[:, 4]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21],
       [ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

array([ 8,  9, 10, 11, 12, 13])

In [9]:
# Ale jeżeli funkcja (z_ij) NIE zależy od wszystkich osi (zmiennych) to NIE można użyć sparse=True
xx_ij, yy_ij = np.meshgrid(x, y, indexing='ij',sparse=False)
z_ij = xx_ij
display(z_ij)
z_ij[:, 4]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

array([0, 1, 2, 3, 4, 5])

### <b> Indeksowanie $xy$ "kartezjańskie"

In [10]:
xx_xy, yy_xy = np.meshgrid(x, y, indexing='xy')
z_xy = xx_xy + 2*yy_xy
display(z_xy)
z_xy[:, 4]

array([[ 0,  1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12, 13],
       [10, 11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20, 21],
       [18, 19, 20, 21, 22, 23]])

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])